import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomePage from "../components/heroSection/homePage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eydean</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon 2.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
